### ISSUE TITLE
Add-On still exit

### ISSUE THREAD

**Issue by Bjoern3003** [Alexandre-io/homeassistant-vcontrol#3]
Hi,

I have tried your Add-On.

But after configuration an start, the Add-On is stopped after a few seconds.

![1673024611](https://user-images.githubusercontent.com/13675579/211061303-747d1eec-b96d-4021-a14f-078188e4e58c.png)

Do you have an Idea, what do I have to do, that the Add-On is not stopped.

**Comment by Alexandre-io** [comment]
Hi @Bjoern3003 !

I have added a debug option in the latest version of the addon (1.5.0). Could you try enabling it and see if the output can be more helpful.

It could be related to the hardware. I only tested the official optolink cable with a raspberry pi 4.

**Comment by Bjoern3003** [comment]
Hi @Alexandre-io 

thank you for your fast response. Now the Add-On is running. 
The Log is looking like this:

![1673114270](https://user-images.githubusercontent.com/13675579/211164114-dc464317-feb7-4a3e-bd8e-90d9f669bf95.png)


Do I have to send a request to the Addon, to get Informations from my viessmann or does the Add-On create own entities?

**Comment by Bjoern3003** [comment]
Yeah, now I get Informations in my mqtt Broker. Did not know, why its now working. But it is :-)

Does your Addon have an event to send commands to vclient?

**Comment by Schm1tz1** [comment]
Hi @Bjoern3003 , maybe I can help you - just set this add-on up like a week ago. The add-on is basically a docker container running vcontrold and vclient with a template to periodically poll data from your Viessmann device and push it to MQTT.  The interval is configured with the "refresh rate" value in seconds and to get the data into entities you need to set up MQTT Sensors (https://www.home-assistant.io/integrations/sensor.mqtt/).
Example snipped from my config:
```
mqtt:
  sensor:
    - name: "Vitodens Brennerstarts"
      state_topic: "openv/getBrennerStarts"

    - name: "Vitodens Brenner Betriebsstunden"
      state_topic: "openv/getBrennerStunden1"

    - name: "Vitodens Brenner Status"
      state_topic: "openv/getBrennerStatus"

    - name: "Vitodens Aussentemperatur"
      state_topic: "openv/getTempA"
      unit_of_measurement: "°C"
      
    - name: "Vitodens Kesseltemperatur Ist"
      state_topic: "openv/getTempKist"
      unit_of_measurement: "°C"

    - name: "Vitodens Kesseltemperatur Soll"
      state_topic: "openv/getTempKsoll"
      unit_of_measurement: "°C"

    - name: "Vitodens Warmwassertemperatur Ist"
      state_topic: "openv/getTempWWist"
      unit_of_measurement: "°C"

    - name: "Vitodens Warmwassertemperatur Soll"
      state_topic: "openv/getTempWWsoll"
      unit_of_measurement: "°C"
```
Check, reload your configuration and you will see the new entities for the Vitodens sensors.
