### ISSUE TITLE
Vitocal200S support / XML file configurable

### ISSUE THREAD

**Issue by RoP09** [Alexandre-io/homeassistant-vcontrol#47]
Hello,

I have a Vitocal 200S which uses a different command set (see https://github.com/openv/openv/wiki/Adressen#adressen-um-werte-abzufragen-oder-zu-setzen), which I already used successfully for years in FHEM / VCONTROL.

Would it be possible to make the vito.xml editable so we can add custom commands to allow other devices?

Thanks!

**Comment by RoP09** [comment]
I downloaded a copy of the addon and created a local addon from it, but no matter what I try it completly ignores any changes from the rootfs/etc/vito.xml. I simply changed the payload of an existing command to one that the 200S understands, but it still sends the old payload.

Could it be that the vito.xml is taken from the original vcontrold (installed from the docker file) instead of the provided one?

**Comment by elasc** [comment]
as far as I understood, you can not modify a file of a installed add-on, as it's running in a container. The only possible configuration is within the config page of the add-on administration in ha.
Having this said, I do have exactly the same issue. Also Vitocal 200-S and also migrating from FHEM. :-)

**Comment by elasc** [comment]
@Alexandre-io would you add the parameters for Vitocal 200-S in your code?

**Comment by Alexandre-io** [comment]
Hi @elasc, could you send me the vito.xml for the 200-S? I will try to find the best way to integrate it into the module.

**Comment by RoP09** [comment]
> as far as I understood, you can not modify a file of a installed add-on, as it's running in a container. The only possible configuration is within the config page of the add-on administration in ha. Having this said, I do have exactly the same issue. Also Vitocal 200-S and also migrating from FHEM. :-)

Yes, that is why I installed it as a custom (local) addon and modified the files before installation, but still it seems it is not using the values I set there (maybe the wrong place?)

**Comment by Alexandre-io** [comment]
Hello @here! I just added the ability to customize the vito.xml file. You just need to create the `vcontrold` directory in the HA configuration files and add the `vito.xml` file.

cf. https://github.com/Alexandre-io/homeassistant-vcontrol/blob/main/vcontrold/DOCS.md#custom-vitoxml-configuration-file

**Comment by mifritscher** [comment]
Does this mean that I the check for the possible device IDs isn't enforced any longer?

Btw, for me the integration of the configuration for the Vitocal200S (device ID 204D) would be very useful as well :-)

**Comment by elasc** [comment]
very nice @Alexandre-io and great support. I've added the modified vito.xml file as custom file as you've implemented this today. Attached please find my file for 204D (Vitocal 200-S).

Commands are getTempA getTempVListM1 getTempVLsollM1 getTempRL17A getTempSpu getUmschaltventil

A bit hacky; I've also added this device in command getTempVListM2 for reading Vorlaufsolltemperatur Anlage as I could not find an implemented command for this reading.
[vito.xml.zip](https://github.com/Alexandre-io/homeassistant-vcontrol/files/13209984/vito.xml.zip)

**Comment by mifritscher** [comment]
Seems to work, thanks :-)

Hint for others: the vito.xml needs to be saved in /config/vcontrold (/config being the root of the "file editor").

My list of commands:
* getTempA:FLOAT
* getTempVListM1:FLOAT
* getTempVListM2:FLOAT
* getTempVLsollM1:FLOAT
* getTempRL17A:FLOAT
* getTempSpu:FLOAT
* getUmschaltventil:FLOAT

My yaml:
```
mqtt:
  binary_sensor:
    - name: Status Umschaltventil
      unique_id: vcontroldgetUmschaltventil
      state_topic: openv/getUmschaltventil
      device_class: running
      value_template: "{% if(value|int == '0') %}OFF{% else %}ON{% endif %}"
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
  sensor:
    - name: Aussentemperatur
      unique_id: vcontroldgetTempA
      device_class: temperature
      state_topic: openv/getTempA
      unit_of_measurement: °C
      value_template: "{{ value | round(2) }}"
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
    - name: Vorlauftemperatur M1
      unique_id: vcontroldgetTempVListM1
      state_topic: openv/getTempVListM1
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
      unit_of_measurement: °C
      value_template: "{{ value | round(2) }}"
    - name: Vorlauftemperatur M2
      unique_id: vcontroldgetTempVListM2
      state_topic: openv/getTempVListM2
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
      unit_of_measurement: °C
      value_template: "{{ value | round(2) }}"
    - name: Vorlaufsolltemperatur M1
      unique_id: vcontroldgetTempVLsollM1
      state_topic: openv/getTempVLsollM1
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
      unit_of_measurement: °C
      value_template: "{{ value | round(2) }}"
    - name: Ruecklauftemperatur 17A
      unique_id: vcontroldgetTempRL17A
      state_topic: openv/getTempRL17A
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
      unit_of_measurement: °C
      value_template: "{{ value | round(2) }}"
    - name: Speichertemperatur unten
      unique_id: vcontroldgetTempSpu
      state_topic: openv/getTempSpu
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
      unit_of_measurement: °C
      value_template: "{{ value | round(2) }}"
```

I think that some more commands should be adaptable for the Vitocal 200S, but this is a thing for the next days ;-)
