### ISSUE TITLE
Set values are cut off too early

### ISSUE THREAD

**Issue by dk1305hb** [Alexandre-io/homeassistant-vcontrol#48]
Hi,

I have noticed that some set commands are not successful if the values have got whitespaces.

Example from Unit "BetriebsArt", enum value "<enum bytes="04" text="H+WW FS"/>":

The set command is cut off after "H+WW"

I think the reason is in vcontrold/rootfs/etc/services.d/vclient_sub/run
Line 19

echo "setBetriebsArt H+WW FS" | cut -d' ' -f2
=H+WW

Maybe solved by
echo "setBetriebsArt H+WW FS" | cut -d' ' -f2-
=H+WW FS

Regards
Daniel

**Comment by Huskerdu24** [comment]
I see a similar issue here:
The payload for the heating shedule doesn’t work at all. I.e. this:

```
select: 
    - name: "HZ01 Timer HZ Mo Sel"
      unique_id: "vcontroldgetTimerMoHeizen"
      state_topic: "openv/getTimerMoHeizen"
      device:
        identifiers: vcontrold
        manufacturer: Viessmann
      command_topic: "openv/setTimerMoHeizen"
      options:
        - "Zeit 1"
        - "Zeit 2"
      command_template: |-
        {% if value == 'Zeit 1' %}
        06:30 08:30 18:30 22:00
        {% elif value == 'Zeit 2' %}
        07:30 10:30 19:30 23:30
        {% endif %}
```
Option "Zeit 1" sends only the first “on”-time in the string = “06:30”. It doesn’t send the whole String "06:30 08:30 18:30 22:00" including the other values.
Hopefully there will be a solution for that at some point as well.
